  # this is the default
#server:
#  port: 8025    #default port where the service will be started
#
eureka:         #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
       defaultZone: http://localhost:8093/eureka/
#      defaultZone: http://localhost/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: execution-engine   #current service name to be used by config server
  profiles:
    active: development
  cloud:
    config:
      uri: http://localhost:8888

  management:
  security:
    enabled: false  #disable the spring security on the management endpoints like /env, /refresh etc.

logging:
  level:
    com.stckroute.execution-engine: DEBUG

