server:
  port: 8025   #default port where the service will be started

eureka:         #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:

    serviceUrl:
      defaultZone: http://13.234.74.67:8093/eureka/
    healthcheck:
      enabled: true

    lease:
      duration: 5

spring:
  application:
    name: execution-engine   #current service name to be used by the eureka server

management:
  security:
    enabled: false  #disable the spring security on the management endpoints like /env, /refresh etc.

logging:
  level:
    com.stckroute.execution-engine: DEBUG