server:
    port: 8022
eureka:         #tells about the Eureka server details and its refresh time
    instance:
        leaseRenewalIntervalInSeconds: 1
        leaseExpirationDurationInSeconds: 2
    client:
        serviceUrl:
            defaultZone: http://localhost:8093/eureka/
        healthcheck:
            enabled: true
        lease:
            duration: 5


management:
    security:
        enabled: false  #disable the spring security on the management endpoints like /env, /refresh etc.

logging:
    level:
        com.stackroute.question-service: DEBUG
