#server:
#  port: 8888
###Local MongoDB config
# spring:
#  data:
#  mongodb:
#   authentication-database: admin
#   database: voting
#   port: 27017
#   host: localhost
#   repositories.enabled: true
###server:
###  port: 8098    #default port where the service will be started
###
eureka:         #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8093/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: voting-service   #current service name to be used by the eureka server
  profiles:
    active: development
  cloud:
    config:
      uri: http://localhost:8888

management:
  security:
    enabled: false  #disable the spring security on the management endpoints like /env, /refresh etc.

#logging:
#  level:
#    com.stckroute.voting-service: DEBUG